### ISSUE TITLE
유저 스페이스 예약 기능 구현 및 예약 기능에 유효성 검사 추가

### ISSUE THREAD

**Issue by heyyjin** [seat-checking/back-end#107]
## Description
유저가 이용 할 스페이스를 예약하는 API를 구현합니다.

## To-do
- [x] 유저 스페이스 예약 API 구현
- [x] 예약 단위 체크 로직 추가 (좌석 예약 API도)
- [x] 당일 예약은 현 시간 기준 3시간 이후부터 가능 (좌석 예약 API도)
- [x] 예약 시간 유효성 체크 (좌석 예약 API도)

## ETC
