### ISSUE TITLE
관리자의 예약 관리를 위해 ReservationStatus enum생성 및 관련 상태 필드 추가

### ISSUE THREAD

**Issue by heyyjin** [seat-checking/back-end#112]
## Description
관리자의 예약 승인 및 거절, 예약 대기 상태를 관리하기 위해 ReservationStatus enum을 생성합니다.
reservation 도메인에 reservationStatus 필드를 추가합니다.

## To-do
- [x] 예약 상태 관리를 위해 ReservationStatus enum class 생성
- [x] 예약 domain에 예약 상태 필드 추가 
- [x] 좌석 및 스페이스 예약시 예약 상태 기본값(예약 대기)이 들어가도록 추가

## ETC
