### ISSUE TITLE
유저 좌석 및 스페이스 예약 취소 기능 구현 

### ISSUE THREAD

**Issue by heyyjin** [seat-checking/back-end#115]
## Description
유저가 예약한 좌석이나 스페이스를 예약 취소하는 기능을 구현합니다.

## To-do
- [x] 유저 좌석 예약 취소 기능 구현
- [x] 유저 스페이스 예약 취소 기능 일부 구현 (스페이스 예약 기획에 따라 디벨롭 후 취소 기능 디벨롭 예정)
- [x] 예약 현황 조회 API의 response에 reservationId 값 추가

## ETC
