### ISSUE TITLE
유저 예약 현황 조회 기능 구현 및 Reservation class에 Store엔티티 추가와 이에 따른 로직 추가

### ISSUE THREAD

**Issue by heyyjin** [seat-checking/back-end#124]
## Description
유저가 내 예약 현황을 조회합니다.

## To-do
- [x] 유저 예약 상태에 따른 내 예약 리스트 조회 기능 구현
- [x] 유저 예약 현황 조회 기능 : 무한스크롤 위한 Slice 처리
- [x] Reservation entity class에 연관관계 관리를 위해 Store 엔티티 추가
- [x] 좌석 혹은 스페이스 예약시, Store도 관리되도록 로직 추가

## ETC
