### ISSUE TITLE
쿠키 사용에 따른 SameSite 값 변경 및 보안 강화 위해 SSL 적용 

### ISSUE THREAD

**Issue by heyyjin** [seat-checking/back-end#131]
## Description
브라우저에서 SameSite=Secure가 기본으로 설정되어있는데, 개발시 다른 호스트끼리 쿠키를 주고받을 수 있도록 하기위해 SameSite=None으로 변경이 필요하다.  
그런데 SameSite값 변경을 위해 HTTPS가 필수, 또 보안 강화를 위해 Letsencrypt를 사용한 SSL 적용 

## To-do
- [x] 사용중인 ec2 서버에 SSL 인증서 설치
- [x] 개발중인 Spring Boot에 적용
- [x] Cookie에 SameSite="None"과 Secure 설정
- [x] 현재 8080은 교육용 등 겹치는 포트가 있어 불편하기 때문에, 사용 포트 변경

## ETC
