### ISSUE TITLE
유저 스페이스 예약 API와 유저 좌석 예약 API에서 예약 정보 받도록 로직 추가

### ISSUE THREAD

**Issue by heyyjin** [seat-checking/back-end#173]
## Description
기획 변경에 따라, 유저 스페이스 예약 API와 유저 좌석 예약 API에 각 가게마다 설정된 예약 정보를 입력받도록 로직을 추가합니다.

## To-do
- [x] 유저 좌석 예약 API에 설정된 이용 정보를 입력받도록 로직 추가
- [x] 유저 스페이스 예약 API에 설정된 이용 정보를 입력받도록 로직 추가
- [x] 유저 스페이스 바로사용 API에 설정된 이용 정보를 입력받도록 로직 추가
- [x] 유저 좌석 바로사용 API에 설정된 이용 정보를 입력받도록 로직 추가
- [x] 커스텀 관련한 모든 부분 Reservation 워딩 Utilization으로 수정

## ETC
