### ISSUE TITLE
직원 등록을 위한 유저 검색 시 이름 필드 삭제 및 예외처리 수정

### ISSUE THREAD

**Issue by 0binn** [seat-checking/back-end#191]
## Description
유저 검색 시 이름을 Response에서 삭제하고, 존재하는 직원의 예외처리를 직원 등록으로 이동하여 수정합니다.

## To-do
- [x] name 필드 삭제
- [x]  예외 처리 코드 이동
- [x] 직원 없을때 에러코드 수정

## ETC
