### ISSUE TITLE
바로 사용 요청 기능 구현 

### ISSUE THREAD

**Issue by heyyjin** [seat-checking/back-end#204]
## Description
유저의 바로 사용 요청 기능 구현 

## To-do
- [x] 관련 엔티티 생성
- [x] 의자 바로 사용 기능 구현 
- [x] 스페이스 바로 사용 기능 구현 
- [x] Reservation과 공통적으로 사용되는 부분은 Utilization으로 옮겨 사용하기 리팩토링

## ETC
