### ISSUE TITLE
특정 의자와 날짜의 유효 이용 시간 조회 API 구현 

### ISSUE THREAD

**Issue by heyyjin** [seat-checking/back-end#272]
## Description
특정 의자와 날짜의 유효 이용 시간을 조회하는 API를 개발합니다.

## To-do
- [x] 특정 의자와 날짜의 유효한 예약 시간 조회
- [x] 특정 의자와 날짜의 유효한 바로 사용 시간 조회
- [x] 예약 상태 '승인'인 데이터에 체크아웃 한 데이터도 포함되어있는 문제 해결 

## ETC
