### ISSUE TITLE
가게 기본 정보 등록 및 확인 시 전화번호 필드 추가

### ISSUE THREAD

**Issue by EllieHyun** [seat-checking/back-end#285]
## Description
가게 기본 정보 등록 및 사용자가 가게 정보를 확인할때 전화번호 필드를 추가합니다.

## To-do
- [ ] 가게에 전화번호 필드 추가
- [ ] 전화번호 설정 로직 추가
- [ ] 사용자 데이터 조회 시 전화번호 응답 필드 추가

## ETC
