### ISSUE TITLE
유저 회원가입 API 구현 

### ISSUE THREAD

**Issue by heyyjin** [seat-checking/back-end#3]
## Description
관리자가 아닌, 일반 유저 회원가입 API를 구현합니다.

## To-do
- [x] 회원 역할 enum 생성
- [x] 이메일 검증 및 중복 확인 API 구현
- [x] 닉네임 검증 및 중복 확인 API 구현
- [x] 유저 회원가입 API 구현 

## ETC
