### ISSUE TITLE
겹치는 시간은 '예약'이나 '바로사용' 안되도록 예외처리 

### ISSUE THREAD

**Issue by heyyjin** [seat-checking/back-end#304]
## Description
이미 누군가 이용중인 시간과 겹치는 시간대로 예약 혹은 바로사용 신청이 들어 온 경우, 예외처리

## To-do
- [ ] 겹치는 시간은 '예약'이나 '바로사용' 안되도록 예외처리 (의자 예약)
- [ ] 겹치는 시간은 '예약'이나 '바로사용' 안되도록 예외처리 (의자 바로사용)
- [ ] 겹치는 시간은 '예약'이나 '바로사용' 안되도록 예외처리 (스페이스 예약)
- [ ] 겹치는 시간은 '예약'이나 '바로사용' 안되도록 예외처리 (스페이스 바로사용)

## ETC
