### ISSUE TITLE
스페이스의 좌석 정보 불러오기 API의 조회 성능 개선을 위한 캐시 도입

### ISSUE THREAD

**Issue by heyyjin** [seat-checking/back-end#311]
## Description
스페이스의 좌석 정보 불러오기 API의 조회 성능 개선을 위해 Ehcache3.x를 도입합니다.

## To-do
- [x] Cache 의존성 설정
- [x] 캐시 환경설정 (xml 파일)
- [x] Ehcache Configuration 추가
- [x] 캐싱 사용하기
- [x] 테스트

## ETC
https://www.ehcache.org/documentation/3.0/
https://www.ehcache.org/documentation/3.10/
