### ISSUE TITLE
[아키텍처 문제 해결] Domain 레이어 생성 및 SOLID

### ISSUE THREAD

**Issue by heyyjin** [seat-checking/back-end#344]
### 🧐 문제 
영속성 객체(entity)와 domain이 구분되지 않고 하나로 관리되고 있습니다. (= 죽은 도메인 문제)
이로 인해, 객체는 수동적이고 모든 코드가 함수 위주로 돌아갑니다. 절차지향적인 코드가 되었습니다.

### 💡 해결 방안 
OOP스러운 도메인들이 협력하는 **domain 계층을 생성**합니다. 이 계층은 **lombok을 제외한 어노테이션이 없는 오브젝트로만 구성**합니다.
**실제 업무**가 각 도메인 영역에서 이루어지도록 합니다.

## To-do
- [x] domain 레이어 생성을 통해, 도메인을 영속성 객체와 구분시키기
- [ ] 도메인 객체 생성
- [ ] 각 도메인의 실제 업무를 도메인 영역에서 구현 

## ETC
